import { Link } from "wouter";

type LegalKind = "privacy" | "terms" | "payroll";
const copy = {
  privacy: { title: "Privacy Policy", eyebrow: "PRIVACY · ကိုယ်ရေးအချက်အလက်", sections: [["Welcome", "Welcome to Zin Min Htet — HR Operations · Payroll · Toolkit. We respect your privacy and are committed to protecting personal information you may provide when using this website, its resources, or our online channels."], ["Information we may collect", "Depending on how you interact with the website, we may collect your name, email address, contact information, information voluntarily provided through forms or inquiries, and basic website usage information such as pages visited and general technical information. We only collect information reasonably necessary for the relevant purpose."], ["How we use information", "Information may be used to respond to inquiries, provide requested resources, improve the website and user experience, maintain security and functionality, and communicate with you when necessary about your request. We do not use personal information for unrelated purposes without appropriate notice."], ["Cookies and analytics", "The website may use cookies or similar technologies to support functionality and understand general usage. Third-party analytics services, where used, may collect technical or usage information under their own privacy policies."], ["Third-party services", "The website may contain links to third-party platforms, including Telegram and LinkedIn. Those services operate under their own terms and privacy policies. We are not responsible for the privacy practices of third-party services."], ["Payroll tools and protected workspace", "Public payroll calculators process estimates in the browser and should not be used with confidential employee data. Telegram access requests and protected-workspace records may be stored to manage access and operate the service."], ["Data security and retention", "We use reasonable measures to protect information and retain it only for as long as reasonably needed for the stated purpose, legal obligations, security, or service administration."], ["Your choices and contact", "You may contact us through the HR Toolkit Telegram channel at https://t.me/ayelay_bot with privacy questions or requests concerning information you provided."], ["Changes to this policy", "We may update this Privacy Policy when the website, services, or applicable requirements change. The latest version will be published on this page with its updated date."]] },
  terms: { title: "Terms of Use", eyebrow: "TERMS · အသုံးပြုမှုစည်းကမ်း", sections: [["Educational use", "The HR game, law references, videos, Zeke guidance and payroll estimator are educational resources. They do not replace a qualified HR, tax, payroll or legal adviser."], ["User responsibility", "Check current Myanmar rules and your organisation's policies before making payroll, employment or payment decisions. Do not enter confidential employee data into the public demo."], ["Service fee", "Any payroll service fee is shown separately from salary, tax and SSB estimates. A displayed fee is informational until a separate service agreement is confirmed."], ["Availability", "We may update content, sources and features to keep the toolkit useful. Public job links belong to their original publishers."]] },
  payroll: { title: "Payroll Calculator Disclaimer", eyebrow: "PAYROLL · အရေးကြီးမှတ်ချက်", sections: [["Estimate only", "This calculator produces an estimate from the values entered. Actual payroll depends on current law, employee eligibility, payroll period, company policy and verified records."], ["Tax and SSB", "PIT, SSB, reliefs, wage bases and contribution limits may change. Confirm current requirements with the relevant Myanmar authority or a qualified practitioner."], ["Service fee separation", "Payroll service fee is not salary, taxable income, PIT or SSB. It is displayed separately so users can see the real service charge without hidden limits."], ["Before use", "Review the result, retain supporting documents, and obtain approval before paying employees or filing an official record."]] },
} as const;

export default function LegalPage({ kind }: { kind: LegalKind }) {
  const page = copy[kind];
  return <main className="legal-page"><header><p className="section-kicker">{page.eyebrow}</p><h1>{page.title}</h1><p className="legal-lede">HR Toolkit · Myanmar HR, Payroll & Workplace Learning Toolkit</p></header><div className="legal-page-body">{page.sections.map(([heading, text]) => <section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}</div><footer><Link href="/">← Back to website</Link><span>Last updated: 2 Oct 2026</span></footer></main>;
}
