import { Link } from "wouter";

type LegalKind = "privacy" | "terms" | "payroll";
const copy = {
  privacy: { title: "Privacy Policy", eyebrow: "PRIVACY · ကိုယ်ရေးအချက်အလက်", sections: [["What we collect", "Payroll calculator inputs are processed in your browser for the estimate. We do not need your salary values to provide the public demo."], ["Zeke and messages", "Zeke is a workplace support widget. Messages and mood selections are intended to remain in this browser and should not contain confidential employee or company information."], ["Telegram and admin", "Telegram access requests and admin records may be stored to operate the protected workspace. They are used for access management, not sold to third parties."], ["Contact", "For privacy questions, contact fzinmin11@gmail.com."]] },
  terms: { title: "Terms of Use", eyebrow: "TERMS · အသုံးပြုမှုစည်းကမ်း", sections: [["Educational use", "The HR game, law references, videos, Zeke guidance and payroll estimator are educational resources. They do not replace a qualified HR, tax, payroll or legal adviser."], ["User responsibility", "Check current Myanmar rules and your organisation's policies before making payroll, employment or payment decisions. Do not enter confidential employee data into the public demo."], ["Service fee", "Any payroll service fee is shown separately from salary, tax and SSB estimates. A displayed fee is informational until a separate service agreement is confirmed."], ["Availability", "We may update content, sources and features to keep the toolkit useful. Public job links belong to their original publishers."]] },
  payroll: { title: "Payroll Calculator Disclaimer", eyebrow: "PAYROLL · အရေးကြီးမှတ်ချက်", sections: [["Estimate only", "This calculator produces an estimate from the values entered. Actual payroll depends on current law, employee eligibility, payroll period, company policy and verified records."], ["Tax and SSB", "PIT, SSB, reliefs, wage bases and contribution limits may change. Confirm current requirements with the relevant Myanmar authority or a qualified practitioner."], ["Service fee separation", "Payroll service fee is not salary, taxable income, PIT or SSB. It is displayed separately so users can see the real service charge without hidden limits."], ["Before use", "Review the result, retain supporting documents, and obtain approval before paying employees or filing an official record."]] },
} as const;

export default function LegalPage({ kind }: { kind: LegalKind }) {
  const page = copy[kind];
  return <main className="legal-page"><header><p className="section-kicker">{page.eyebrow}</p><h1>{page.title}</h1><p className="legal-lede">Zin Min Htet · Myanmar HR, Payroll & Workplace Learning Toolkit</p></header><div className="legal-page-body">{page.sections.map(([heading, text]) => <section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}</div><footer><Link href="/">← Back to website</Link><span>Last reviewed: 30 Sep 2026</span></footer></main>;
}
