import { useMemo } from "react";
import { ArrowRight, FileText, History, MessageCircle, ShieldCheck, Sparkles } from "lucide-react";
import { trpc } from "@/lib/trpc";
import "./clean-product.css";

export default function UserDashboard() {
  const me = trpc.auth.me.useQuery();
  const docs = useMemo(() => { try { return JSON.parse(localStorage.getItem("zeke-clean-documents") || "[]") as Array<{ name: string; createdAt: string }>; } catch { return []; } }, []);
  return <main className="clean-page"><header className="clean-page-header"><div><p className="clean-eyebrow">Zeke · Personal workspace</p><h1>{me.data?.name ? `Welcome back, ${me.data.name}.` : "Your Zeke workspace."}</h1><p>Keep your working documents, service shortcuts, and recent activity in one place. Sensitive employee data should only be used in an approved private workspace.</p></div><a className="clean-back" href="/">Back to Zeke</a></header><section className="clean-grid"><div className="clean-card"><p className="clean-eyebrow">Quick access</p><h2>Continue where you left off.</h2><div className="clean-list"><a className="clean-list-row" href="/workspace"><FileText size={18}/><span><strong>HR workspace</strong><small>Forms, documents, guidance, and generator</small></span><ArrowRight size={16}/></a><a className="clean-list-row" href="/?section=services"><Sparkles size={18}/><span><strong>Payroll and protected services</strong><small>Request approval and open the toolkit</small></span><ArrowRight size={16}/></a><a className="clean-list-row" href="/plans"><ShieldCheck size={18}/><span><strong>Plans and access</strong><small>See what is available in each plan</small></span><ArrowRight size={16}/></a></div></div><div className="clean-card clean-note"><h3>Workspace snapshot</h3><p><strong>{docs.length}</strong> browser document{docs.length === 1 ? "" : "s"} saved</p><p><strong>{me.data ? "Signed in" : "Public session"}</strong></p><p className="clean-muted">Conversation history and service records become available after the account connection is configured.</p></div></section><section className="clean-card" style={{maxWidth:1180,margin:"20px auto 0"}}><p className="clean-eyebrow">Activity</p><h2>Recent activity</h2><div className="clean-list"><div className="clean-list-row"><History size={18}/><span><strong>Workspace opened</strong><small>Use the HR workspace to create or download a working record.</small></span></div><div className="clean-list-row"><MessageCircle size={18}/><span><strong>Ask Zeke</strong><small>Ask a question and follow the recommended service link.</small></span></div></div></section></main>;
}
